HD-2757 Improve reliability of rust CI
We are getting a bunch of instances of this

```
error: linking with `cc` failed: exit status: 1
  |
  = note:  "cc" "-m64" "/tmp/rustcDSuBoy/symbols.o" "<17 object files omitted>" "-Wl,--as-needed" "-Wl,-Bstatic" "/home/runner/work/heartbeat-case/heartbeat-case/target/debug/deps/{libmockito-226b9f9132a38bd8.rlib,libassert_json_diff-c2ad4dae7ab68204.rlib,libsimilar-d55a9a81a845c1ba.rlib,libcolored-2ec3c5a612c85523.rlib,libtextwrap-6449486e9165af3d.rlib,libunicode_linebreak-
```
In our rust tests.

This is due to the rust linker running out of memory